<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net6.0</TargetFrameworks>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Title>JitInspect</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>1.0.2</Version>
        <Copyright>Copyright (c) 2024 Akeit0</Copyright>
        <Authors>Akeit0</Authors>
        <Description>JitInspect disassembles JIT compiled managed methods to a x86/x64/Arm64 ASM.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Iced" Version="1.21.0"/>
        <PackageReference Include="Gee.External.Capstone" Version="2.3.0"/>
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>
        <PackageReference Include="Microsoft.Diagnostics.Runtime" Version="4.0.726401"/>
        <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.3"/>
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="..\..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
</Project>
